### ISSUE TITLE
mrcli company: no output or error generated if ~/Documents is missing

### ISSUE THREAD

**Issue by jgoodie** [mediumroast/mediumroast_js#49]
mrcli company --output=csv 

If ~/Documents is missing, mrcli will not generate a warning or error yet will return 0 as if nothing is wrong.

**Comment by miha42-github** [comment]
The issue was the definition of ~/Documents was incorrect in mrcli-setup.js.  This was resolved and as needed the Documents directory will be created.  We should test this on a windows system to see if it works correctly or if we need to check the OS and choose a different behavior for Windows. @jgoodie please confirm this is working. @helloleodr when can we try on Windows?

**Comment by miha42-github** [comment]
Verified the patch creates the Documents folder.  For Windoze @helloleodr needs to do some work.

**Comment by miha42-github** [comment]
Verified and closing
